import type { EtapaContratacion } from "@prisma/client";

/**
 * Sugerencias de categoría/nombre de documento por etapa, tomadas de los
 * nombres de archivo reales de `Modelo/Contratacion/Formatos/FORMATOS/**`
 * (119 formatos oficiales A-BS-FOxx). A propósito NO son un catálogo cerrado
 * ni generan un formulario por formato — son solo sugerencias de un
 * `<datalist>` sobre un campo de texto libre (`DocumentoContrato.categoria`),
 * para no convertir este módulo en un ERP con un formulario por cada uno de
 * los 119 formatos.
 */
export const CATEGORIAS_SUGERIDAS: Record<EtapaContratacion, string[]> = {
  PRECONTRACTUAL: [
    "Aceptación de oferta / invitación pública",
    "Acta administrativa de declaratoria de desierto",
    "Acta administrativa de justificación",
    "Acta de aprobación de garantías",
    "Acta administrativa de adjudicación a único oferente",
    "Acta administrativa de adjudicación",
    "Acta administrativa de apertura",
    "Acta de audiencia de apertura de sobre económico (enajenación)",
    "Acta de audiencia de apertura de sobre económico",
    "Acta de audiencia de asignación de riesgos y aclaración de pliegos",
    "Acta de audiencia de precalificación",
    "Acta de audiencia de sorteo de consolidación de oferentes",
    "Acta de audiencia de adjudicación",
    "Acta de evaluación de comité",
    "Acta de evaluación de cumplimiento de requisitos",
    "Acta de evaluación de idoneidad (entidad sin ánimo de lucro)",
    "Acta de evaluación de idoneidad",
    "Acta de inclusión de objeto contractual",
    "Acta de respuesta a observaciones",
    "Anexo complementario",
    "Anexo complementario — arrendamiento",
    "Anexo complementario — comodato",
    "Anexo complementario — consultoría",
    "Anexo complementario — contrato de prestación de servicios",
    "Anexo complementario — suministro",
    "Aviso de convocatoria a precalificación (concurso de méritos)",
    "Aviso de convocatoria",
    "Aviso de convocatoria para licitación pública",
    "Aviso de no limitación a Mipymes",
    "Certificación de contrato con objeto igual",
    "Certificado de existencia del Plan Anual de Adquisiciones",
    "Comprobante de oferta",
    "Constancia de desglose",
    "Creación, modificación o inclusión al Plan Anual de Adquisiciones",
    "Estudio del sector — mínima cuantía y contratación directa",
    "Estudio del sector — diferente a mínima cuantía y contratación directa",
    "Estudios y documentos previos",
    "Invitación a presentar propuesta",
    "Invitación a presentar propuesta (único oferente)",
    "Listado de verificación — concurso de méritos",
    "Listado de verificación — contratación directa diferente a CPS",
    "Listado de verificación — contrato de prestación de servicios",
    "Listado de verificación — licitación pública",
    "Listado de verificación — mínima cuantía",
    "Listado de verificación — selección abreviada, menor cuantía",
    "Listado de verificación — selección abreviada, subasta inversa",
    "Requerimiento técnico",
    "Solicitud de personal idóneo",
  ],
  CONTRACTUAL: [
    "Acta aclaratoria contractual",
    "Acta aclaratoria o modificatoria de contrato",
    "Acta de cambio de supervisor",
    "Acta de audiencia por presunto incumplimiento de contrato",
    "Acta de concertación — adición de plazo y valor",
    "Acta de concertación para modificación",
    "Acta de concertación de prórroga del plazo",
    "Acta de concertación — adición en valor y/o prórroga del plazo",
    "Acta de inicio de la ejecución",
    "Acta de inicio — prestación de servicios profesionales y apoyo a la gestión",
    "Acta de mayores y menores cantidades",
    "Acta de recibo definitivo — contrato de obra",
    "Acta de recibo — pago parcial",
    "Acta de suspensión y reinicio",
    "Acta de entrega de anticipo",
    "Designación de supervisor",
    "Documento de autorización de cesión",
    "Formato único de informe de cumplimiento",
    "Informe de supervisión",
    "Informe de supervisión — obra pública",
    "Informe de presunto incumplimiento de contrato",
  ],
  POSTCONTRACTUAL: [
    "Acta de cierre de expedientes",
    "Acta de liquidación de mutuo acuerdo",
    "Acta de recibo definitivo y pago final",
    "Acta de terminación por mutuo acuerdo",
    "Formato de evaluación de proveedores",
  ],
};
