export const ESTADOS_EXPEDIENTE = [
  "RADICADO",
  "EN_TRAMITE",
  "INFORMACION_ADICIONAL_REQUERIDA",
  "SUSPENDIDO",
  "APROBADO",
  "NEGADO",
  "DESISTIDO",
  "ARCHIVADO",
  "RECHAZADO",
] as const;

export const ESTADOS_TERMINALES_EXPEDIENTE = ["APROBADO", "NEGADO", "DESISTIDO", "ARCHIVADO", "RECHAZADO"] as const;
